version: '3.8'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
  web:
    image: nginx
    volumes:
       - ./templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80

networks:
  dockernet:
    external: true